apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
  labels:
    app: chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: weed3583/cloudhop:latest
        ports:
        - containerPort: 5001
        env:
        - name: REDIS_URL
          value: redis://redis-service:6379/0
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  labels:
    app: chat-app
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
